apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.password | quote }}
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CREATE_TOPICS: "order-events:1:1"
  ORDER_SERVICE_URL: {{ .Values.config.orderServiceUrl | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.config.productServiceUrl | quote }}
  USER_SERVICE_URL: {{ .Values.config.userServiceUrl | quote }}
