apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CREATE_TOPICS: "order-events:1:1"
  ORDER_SERVICE_URL: "order-service:3003"
  PRODUCT_SERVICE_URL: "product-service:3005"
  USER_SERVICE_URL: "user-service:3004"
