name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api-gateway
        run: |
          if git diff --name-only HEAD~1 | grep -q "^api-gateway/"; then
            docker build -t ${{ secrets.DOCKERHUB_USER }}/ecom_api_gateway:${{ github.sha }} api-gateway
            docker push ${{ secrets.DOCKERHUB_USER }}/ecom_api_gateway:${{ github.sha }}
          fi

      - name: Build and push product-service
        run: |
          if git diff --name-only HEAD~1 | grep -q "^product-service/"; then
            docker build -t ${{ secrets.DOCKERHUB_USER }}/ecom_product_service:${{ github.sha }} product-service
            docker push ${{ secrets.DOCKERHUB_USER }}/ecom_product_service:${{ github.sha }}
          fi

      - name: Build and push user-service
        run: |
          if git diff --name-only HEAD~1 | grep -q "^user-service/"; then
            docker build -t ${{ secrets.DOCKERHUB_USER }}/ecom_user_service:${{ github.sha }} user-service
            docker push ${{ secrets.DOCKERHUB_USER }}/ecom_user_service:${{ github.sha }}
          fi

      - name: Build and push order-service
        run: |
          if git diff --name-only HEAD~1 | grep -q "^order-service/"; then
            docker build -t ${{ secrets.DOCKERHUB_USER }}/ecom_order_service:${{ github.sha }} order-service
            docker push ${{ secrets.DOCKERHUB_USER }}/ecom_order_service:${{ github.sha }}
          fi

      - name: Build and push notification-service
        run: |
          if git diff --name-only HEAD~1 | grep -q "^notification-service/"; then
            docker build -t ${{ secrets.DOCKERHUB_USER }}/ecom_notification_service:${{ github.sha }} notification-service
            docker push ${{ secrets.DOCKERHUB_USER }}/ecom_notification_service:${{ github.sha }}
          fi
